#travisCI
language: java
jdk: openjdk8

branches:
 only: master

#mvn build
script: ./mvnw clean package -DskipTests=true


notifications:
email:
recipients: yoonchul15@gmail.com


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  bucket: jaeyoon-worldcup-deploy # 6-3-3에서 생성한 S3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
   repo: yooncheolkim/worldCup #Github 주소
   branch: master